name: Tokenizer API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @xenova/transformers

      - name: Run tokenizer
        run: |
          echo 'import { pipeline } from "@xenova/transformers";

          const prompt = "A dog running through a sunny field.";

          async function run() {
            const clipL = await pipeline("feature-extraction", "Xenova/clip-vit-base-patch32");
            const clipG = await pipeline("feature-extraction", "Xenova/clip-vit-large-patch14");
            const t5 = await pipeline("feature-extraction", "Xenova/t5-base");
            const llama = await pipeline("feature-extraction", "Xenova/phi-1_5");

            const clipLTokens = await clipL.tokenizer(prompt);
            const clipGTokens = await clipG.tokenizer(prompt);

            const t5Tokens = await t5.tokenizer(prompt, {
              padding: true,
              truncation: true,
              max_length: 128
            });

            const injected = `<|start_header_id|>system<|end_header_id|>\n\nDescribe the video by detailing the following aspects: 1. The main content and theme of the video.2. The color, shape, size, texture, quantity, text, and spatial relationships of the objects.3. Actions, events, behaviors temporal relationships, physical movement changes of the objects.4. background environment, light, style and atmosphere.5. camera angles, movements, and transitions used in the video:<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n${prompt}<|eot_id|>`;

            const llamaTokens = await llama.tokenizer(injected);

            console.log("CLIP-L tokens:", clipLTokens.input_ids.length);
            console.log("CLIP-G tokens:", clipGTokens.input_ids.length);
            console.log("T5 (base) tokens:", t5Tokens.input_ids.length);
            console.log("Phi-1.5 tokens:", llamaTokens.input_ids.length);
          }

          run();' > run-tokenizer.mjs

          node run-tokenizer.mjs
